[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
reward_system = "EBovcnX1UXsxPuyMd5yUA1Xc1Ld89wEVFCMJVpS16T4A"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Mainnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/*.ts"
